- name: Playbook for Desktop Fedora with KDE
  hosts: localhost
  tasks:
  -   name: Install git
      become: yes
      package:
          name: git
          state: present
  -   name: Install build essential equal
      become: yes
      package:
          name: make, automake, gcc, gcc-c++, kernel-devel
          state: present
  -   name: Install Libreoffice
      become: yes
      package:
          name: libreoffice
          state: present
  -   name: Install DNF-Dragora
      become: yes
      package:
          name: dnfdragora
          state: present
  -   name: Remove Kwrite
      become: yes
      package:
          name: kwrite
          state: absent
  -   name: Install Kate
      become: yes
      package:
          name: kate
          state: present
  -   name: Install VIM
      become: yes
      package:
          name: vim
          state: present
  -   name: java-openjdk 
      become: yes
      package:
          name: java-openjdk
          state: present
  -   name: Install JavaFX
      become: yes
      package:
          name: openjfx
          state: present
  -   name: fedora-workstation-repositories
      become: yes
      package:
          name: fedora-workstation-repositories
          state: present
  -   name: activate Chrome Repo
      become: yes
      command: dnf config-manager --set-enabled google-chrome
  -   name: Install Chrome
      become: yes
      package:
          name: google-chrome-stable
          state: present
  -   name: Install Thunderbird
      become: yes
      package:
          name: thunderbird
          state: present
  -   name: Add the flathub flatpak repository remote to the user installation
      flatpak_remote:
          name: flathub
          state: present
          flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
          method: user
  -   name: Install the gimp package from flathub for current user
      flatpak:
          name: org.gimp.GIMP
          state: present
          method: user
  -   name: Install the gimp package from flathub for current user
      flatpak:
          name: org.gimp.GIMP
          state: present
          method: user
  -   name: Install the octave package from flathub
      flatpak:
          name: org.octave.Octave
          state: present
          method: user
  -   name: Install the vlc package from flathub
      flatpak:
          name: org.videolan.VLC
          state: present
          method: user
  -   name: Install the PyCharm package from flathub
      flatpak:
          name: com.jetbrains.PyCharm-Community
          state: present
          method: user
  -   name: Install Maven
      become: true
      package:
          name: maven
          state: present
  -   name: Autoremove unneeded packages installed as dependencies
      become: yes
      dnf:
          autoremove: yes
  -   name: Install KeepassX
      become: true
      package:
          name: keepassxc
          state: present
  -   name: Remove Nano default
      become: yes
      package:
          name: nano-default-editor
          state: absent
  -   name: Make VIM default
      become: yes
      package:
          name: vim-default-editor
          state: present
  -   name: Install steam
      become: yes
      package:
          name: steam
          state: present
  