-   hosts: localhost
    tasks:
        -   name: Install git
            become: true
            package:
                name: git
                state: present
        -   name: Install build essential equal
            become: true
            package:
                name: make, automake, gcc, gcc-c++, kernel-devel
                state: present
        -   name: Install DNF-Dragora
            become: true
            package:
                name: dnfdragora
                state: present
        -   name: Install KeepassX
            become: true
            package:
                name: keepassxc
                state: present      
        -   name: Install Kate
            become: true
            package:
                name: kate
                state: present
        -   name: Install arc-theme
            become: true
            package:
                name: arc-theme
                state: present
        -   name: Install Maven
            become: true
            package:
                name: maven
                state: present                          

