-   hosts: localhost
    tasks:
        -   name: Install git
            become: true
            package:
                name: git
                state: present
        -   name: Install build essential equal
            become: true
            package:
                name: make, automake, gcc, gcc-c++, kernel-devel
                state: present
        -   name: Install DNF-Dragora
            become: true
            package:
                name: dnfdragora
                state: present
        -   name: Install Do not disturb gnome
            become: true
            package:
                name: gnome-shell-extension-do-not-disturb-button
                state: present
        -   name: Install Gnome-Icon Support
            become: true
            package:
                name: gnome-shell-extension-topicons-plus
                state: present
        -   name: Install Gnome-Pomodoro
            become: true
            package:
                name: gnome-shell-extension-pomodoro
                state: present  
        -   name: Install KeepassX
            become: true
            package:
                name: keepassxc
                state: present      
        -   name: Install Kate
            become: true
            package:
                name: kate
                state: present
        -   name: Uninstall Firefox
            become: true
            package:
                name: firefox
                state: absent
        -   name: Add the flathub flatpak repository remote to the user installation
            flatpak_remote:
                name: flathub
                state: present
                flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
                method: user
        -   name: Install Firefox
            flatpak:
                name: org.mozilla.firefox
                state: present
                method: user
        -   name: Install nextcloud
            flatpak:
                name: org.nextcloud.Nextcloud
                state: present
                method: user

